apiVersion: am.argocd/v1
kind: ServiceDeploy
service: am-portfolio
enabled: true
owners: portfolio
source:
  repo: am-portfolio
  path: argocd.yaml
chart:
  repoURL: https://github.com/AM-Portfolio/am-pipelines.git
  path: argocd.yaml
  targetRevision: main
helm:
  releaseName: am-portfolio
  valuesPath: helm
valuesRepoURL: https://github.com/AM-Portfolio/am-portfolio.git
valuesTargetRevision: main
envs:
  prod:
    enabled: true
    namespace: am-apps-prod
