version: '3.8'


services:
  am-portfolio-service:
    container_name: am-portfolio-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    environment:
      # Application Configuration
      AM_MARKET_DATA_API_URL: ${AM_MARKET_DATA_API_URL}

      # Kafka Configuration
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

      # Spring Profile
      SPRING_PROFILES_ACTIVE: docker

      # MongoDB Configuration
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_AUTHENTICATION_DATABASE: admin

      # Redis Configuration
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        echo "=== AM Portfolio Service Environment Variables ==="
        echo "Database URL: $${SPRING_DATASOURCE_URL}"
        echo "Database User: $${SPRING_DATASOURCE_USERNAME}"
        echo "Kafka Servers: $${SPRING_KAFKA_BOOTSTRAP_SERVERS}"
        echo "Kafka Group: $${SPRING_KAFKA_CONSUMER_GROUP_ID}"
        echo "Max Retries: $${AM_PORTFOLIO_MAX_RETRIES}"
        echo "=== Starting AM Portfolio Service ==="
        java -jar app.jar
    ports:
      - "8082:8082"
    networks:
      - market-data-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: ${AM_PORTFOLIO_MAX_RETRIES}
    restart: unless-stopped

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:

networks:
  market-data-network:
    driver: bridge
