apiVersion: v1
kind: Service
metadata:
  name: am-portfolio
  labels:
    app: am-portfolio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: am-portfolio
