#mongo
MONGO_URL: mongodb://admin:password@localhost:27017/portfolio?authSource=admin
MONGO_DATABASE: market_data
MONGO_USERNAME: admin
MONGO_PASSWORD: password

server:
  port: 8081  # Using a different port than the service

spring:
  application:
    name: portfolio-api
    # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin
  # Disable JDBC auto-configuration since we're using MongoDB
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging Configuration
logging:
  level:
    com.portfolio.api: INFO
    org.springframework: WARN
