server:
  port: 8081  # Using a different port than the service

spring:
  application:
    name: portfolio-api

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging Configuration
logging:
  level:
    com.portfolio.api: INFO
    org.springframework: WARN
