# am-portfolio Preprod Overrides

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

vault:
  secretPaths:
    auth:
      path: apps/data/preprod/services/am-auth
    infra:
      path: apps/data/preprod/infra/postgres
    portfolio:
      path: apps/data/preprod/services/am-portfolio

ingress:
  hosts:
    - host: portfolio.preprod.am-portfolio.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: portfolio-tls
      hosts:
        - portfolio.preprod.am-portfolio.com
