vault:
  secretPaths:
    auth:
      mappings:
        JWT_SECRET: "JWT_SECRET"
        INTERNAL_SECRET_KEY: "SECRET_KEY"
    portfolio:
      # No mappings needed, defaults to dump-all uppercased
    market-data:
      mappings:
        MARKET_DATA_API_URL: "URL"
    mongodb:
      mappings:
        MONGODB_CONNECTION_URL: "url"
        SPRING_DATA_MONGODB_URI: "url"
    kafka:
      mappings:
        KAFKA_BOOTSTRAP_SERVERS: "bootstrap_servers"
        SPRING_KAFKA_BOOTSTRAP_SERVERS: "bootstrap_servers"
        KAFKA_JAAS_CONFIG: "__jaas__"
        KAFKA_USERNAME: "username"
        KAFKA_PASSWORD: "password"
    redis:
      mappings:
        SPRING_DATA_REDIS_HOST: "host"
        SPRING_DATA_REDIS_PASSWORD: "password"
        SPRING_DATA_REDIS_PORT: "port"
