spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: am-portfolio-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    #redisendpoint: redis-17365.c325.us-east-1-4.ec2.redns.redis-cloud.com:17365
    redisendpoint: localhost:6379
    redis:
      portfolio:
        ttl: 1800  # 30 minutes in seconds
        key-prefix: "portfolio:analysis:"
      market-index:
        ttl: 900  # 15 minutes in seconds
        key-prefix: "market-index:indices:"

app:
  kafka:
    portfolio:
      consumer:
        id: am-portfolio-group
        enabled: false
      topic: am-portfolio-topic
    stock:
      consumer:
        id: am-stock-group
        enabled: true
      topic: am-stock-price-update
    market-index:
      consumer:
        id: am-market-index-group
        enabled: true
      topic: am-market-index-update

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.portfolio: DEBUG
    org.hibernate.SQL: DEBUG
