spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: am-portfolio-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        fetch.max.bytes: 1048576
        max.partition.fetch.bytes: 524288
        fetch.max.wait.ms: 500
        max.poll.records: 100
  data:
    redisendpoint: localhost:6379
    redis:
      portfolio:
        ttl: 1800  # 30 minutes in seconds
        key-prefix: "portfolio:analysis:"
      market-index:
        ttl: 900  # 15 minutes in seconds
        key-prefix: "market-index:indices:"

app:
  persistence:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/portfolio?authSource=admin
      database: portfolio
  kafka:
    portfolio:
      consumer:
        id: am-portfolio-group
        enabled: true
      topic: am-portfolio-topic
    stock:
      consumer:
        id: am-stock-group.v1
        enabled: false
      topic: am-stock-price-update
    market-index:
      consumer:
        id: am-market-index-group
        enabled: false
      topic: am-market-index-update

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 20
    min-spare-threads: 10
    max-connections: 200

logging:
  level:
    com.portfolio: INFO
    org.springframework.kafka: INFO
