name: Portfolio Publish

on:
  push:
    branches: ["main", "develop", "fix/**", "hotfix/**", "feature/**", "feat/**"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  publish:
    name: Publish AM Portfolio
    permissions:
      contents: write
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: "java"
      working_directory: "."
      image_name: "am-portfolio"
      build_context: "."
    secrets: inherit
# Trigger new push
