name: Publish Portfolio Service

on:
  push:
    branches: 
      - main
      - develop
      - "hotfix/*"

jobs:
  publish:
    uses: AM-Portfolio/am-pipelines/.github/workflows/publish-library.yml@main
    with:
      language: java
      working_directory: .
    secrets: inherit
